# Form implementation generated from reading ui file 'pokedex.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(493, 761)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Layout = QtWidgets.QLabel(parent=self.centralwidget)
        self.Layout.setGeometry(QtCore.QRect(0, 0, 491, 741))
        self.Layout.setText("")
        self.Layout.setPixmap(QtGui.QPixmap("Img/principal/Poke (1) (1).png"))
        self.Layout.setScaledContents(True)
        self.Layout.setObjectName("Layout")
        self.Description = QtWidgets.QLabel(parent=self.centralwidget)
        self.Description.setGeometry(QtCore.QRect(150, 600, 210, 111))
        self.Description.setStyleSheet("background-color: transparent;\n"
"color: black;\n"
"font-family: \"Press Start 2P\";\n"
"font-size: 8pt;\n"
"")
        self.Description.setObjectName("Description")
        self.NombreP = QtWidgets.QLabel(parent=self.centralwidget)
        self.NombreP.setGeometry(QtCore.QRect(30, 540, 221, 61))
        self.NombreP.setStyleSheet("background-color: transparent;\n"
"color: black;\n"
"font-family: \"Press Start 2P\";\n"
"font-size: 8pt;\n"
"")
        self.NombreP.setObjectName("NombreP")
        self.Tipo = QtWidgets.QLabel(parent=self.centralwidget)
        self.Tipo.setGeometry(QtCore.QRect(260, 540, 221, 61))
        self.Tipo.setStyleSheet("background-color: transparent;\n"
"color: black;\n"
"font-family: \"Press Start 2P\";\n"
"font-size: 8pt;\n"
"")
        self.Tipo.setObjectName("Tipo")
        self.Pokedex = QtWidgets.QLabel(parent=self.centralwidget)
        self.Pokedex.setGeometry(QtCore.QRect(210, 50, 221, 61))
        self.Pokedex.setStyleSheet("background-color: transparent;\n"
"color: black;\n"
"font-family: \"Press Start 2P\";\n"
"font-size: 8pt;\n"
"")
        self.Pokedex.setObjectName("Pokedex")
        self.LED = QtWidgets.QLabel(parent=self.centralwidget)
        self.LED.setGeometry(QtCore.QRect(380, 620, 64, 64))
        self.LED.setStyleSheet("background-color: gray;\n"
"border-radius: 30px;\n"
"border: 2px solid black;\n"
"min-width: 60px;\n"
"min-height: 60px;\n"
"max-width: 60px;\n"
"max-height: 60px;\n"
"")
        self.LED.setText("")
        self.LED.setObjectName("LED")
        self.PokemonIm = QtWidgets.QLabel(parent=self.centralwidget)
        self.PokemonIm.setGeometry(QtCore.QRect(40, 130, 411, 401))
        self.PokemonIm.setText("")
        self.PokemonIm.setPixmap(QtGui.QPixmap("Img/principal/Charizard Pixel Art.jpg"))
        self.PokemonIm.setScaledContents(True)
        self.PokemonIm.setObjectName("PokemonIm")
        self.Adelante = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Adelante.setGeometry(QtCore.QRect(90, 640, 31, 21))
        self.Adelante.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Adelante.setText("")
        self.Adelante.setObjectName("Adelante")
        self.Atras = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Atras.setGeometry(QtCore.QRect(40, 640, 31, 21))
        self.Atras.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Atras.setText("")
        self.Atras.setObjectName("Atras")
        self.Random = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Random.setGeometry(QtCore.QRect(70, 610, 21, 31))
        self.Random.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Random.setText("")
        self.Random.setObjectName("Random")
        self.Menu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Menu.setGeometry(QtCore.QRect(70, 660, 21, 31))
        self.Menu.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Menu.setText("")
        self.Menu.setObjectName("Menu")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 640, 21, 21))
        self.label.setStyleSheet("background-color: rgb(111, 111, 111);\n"
"background-color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir_pokedex = QtGui.QAction(parent=MainWindow)
        self.actionAbrir_pokedex.setObjectName("actionAbrir_pokedex")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Description.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">PRESIONE UN BOTÓN</span></p></body></html>"))
        self.NombreP.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Nombre pokémon</span></p></body></html>"))
        self.Tipo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Tipo</span></p></body></html>"))
        self.Pokedex.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">POKÉDEX</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", ""))
        self.actionAbrir_pokedex.setText(_translate("MainWindow", "Abrir pokedex"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
